import Head from 'next/head';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1 className='text-5xl font-bold underline text-center mt-5'>
        Underconstruction
      </h1>
      <ul className='text-center mt-10'>
        <li>Tailwind</li>
        <li>Formik & Yup</li>
      </ul>
    </>
  );
}
